//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class etudiant
    {
        public string cne { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string sexe { get; set; }
        public Nullable<System.DateTime> date_naissance { get; set; }
        public string adresse { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public int id_filiere { get; set; }
        public string photo { get; set; }
    
        public virtual filiere filiere { get; set; }
    }
}
