//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exo3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoleEntities : DbContext
    {
        public EcoleEntities()
            : base("name=EcoleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<etudiant> etudiants { get; set; }
        public virtual DbSet<filiere> filieres { get; set; }
        public virtual DbSet<stat> stats { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
